export let courseData = [
  {
    course_id: 1,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Service Design Essentials",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 2,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Software Developer ",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 3,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "UX/UI Design Beginer",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 4,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Product Design for Business",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 5,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Service Design Essentials",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 6,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Service Design Essentials",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 7,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "UX/UI Design Beginner",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 8,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",

    coursename: "Service Design Essentials",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 9,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",

    coursename: "Software Developer",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 10,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Software Developer",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 11,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Software Developer",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
  {
    course_id: 12,
    coursetype: "Course",
    coverimg: "http://dummyimage.com/350x350.png/dddddd/000000",
    coursename: "Software Developer",
    coursedetail: "Lorem ipsum dolor sit amet, conse ctetur adipiscing elit.",
    coursesummary: "6 Lesson",
    totallearningtime: "6 Hours",
  },
];